# Generated by Django 4.2.18 on 2025-02-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0004_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='full_name',
            field=models.CharField(default='Admin', max_length=255),
        ),
    ]
