# Generated by Django 4.2.18 on 2025-02-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0009_user_experience_level_user_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_login',
        ),
    ]
