# Generated by Django 4.2.18 on 2025-02-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0019_quiz_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_active',
        ),
    ]
