# Generated by Django 4.2.18 on 2025-02-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0021_question_created_at_question_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
    ]
