# Generated by Django 4.2.18 on 2025-03-01 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0026_delete_passwordresetrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('registration', 'User Registration'), ('password_reset', 'Password Reset'), ('course_enrollment', 'Course Enrollment'), ('quiz_attempt', 'Quiz Attempt')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cgs.user')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
