# Generated by Django 4.2.18 on 2025-03-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0030_remove_material_video_file_remove_material_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrollment_link',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
