# Generated by Django 4.2.18 on 2025-03-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0032_material_video_file_alter_material_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.TextField(help_text='Text content or video embed URL'),
        ),
    ]
