# Generated by Django 4.2.18 on 2025-03-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0035_remove_material_video_file_alter_material_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='content',
        ),
        migrations.AddField(
            model_name='material',
            name='text_content',
            field=models.TextField(blank=True, help_text='Content for text materials', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file', null=True, upload_to='course_videos/'),
        ),
        migrations.AddField(
            model_name='material',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or other video embed URL', null=True),
        ),
    ]
