# Generated by Django 4.2.18 on 2025-03-10 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0036_remove_material_content_material_text_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='text_content',
        ),
        migrations.RemoveField(
            model_name='material',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='material',
            name='video_url',
        ),
        migrations.AddField(
            model_name='material',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, help_text='Text content or video embed URL'),
            preserve_default=False,
        ),
    ]
