# Generated by Django 4.2.18 on 2025-03-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0037_remove_material_text_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.FileField(blank=True, help_text='Upload a video file for Video Material or enter text for Text Material', null=True, upload_to='materials/'),
        ),
    ]
