# Generated by Django 4.2.18 on 2025-03-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0043_course_enrollment_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrollment_link',
        ),
    ]
