# Generated by Django 4.2.18 on 2025-03-15 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0044_remove_course_enrollment_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgs.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgs.user')),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
