# Generated by Django 4.2.18 on 2025-02-09 04:51

import LMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblAdminlogin',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=30)),
                ('regdate1', models.DateField(auto_now=True)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tblcourse',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=30)),
                ('coursefee', models.IntegerField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('CreatedBy', models.CharField(blank=True, max_length=15, null=True)),
                ('CreatedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblEmpCourse',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ContactNo', models.CharField(max_length=20)),
                ('Course', models.CharField(max_length=50, null=True)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tblEmpDetails',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ContactNo', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=600)),
                ('Designation', models.CharField(max_length=50)),
                ('Course', models.CharField(max_length=50, null=True)),
                ('Password', models.CharField(max_length=30)),
                ('Createdate', models.DateField(auto_now=True)),
                ('Modifydate', models.DateField(auto_now=True)),
                ('isActive', models.BooleanField(default=False)),
                ('isDeactive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tblLogin',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tblMaterial',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(blank=True, max_length=30, null=True)),
                ('Topic', models.CharField(max_length=100)),
                ('VideoMaterial', models.FileField(null=True, upload_to=LMS.models.upload_video_to, validators=[LMS.models.validate_video_file])),
                ('TextMaterial', models.FileField(blank=True, null=True, upload_to='TextMaterial/')),
                ('Program', models.FileField(blank=True, null=True, upload_to='Program/')),
                ('isActive', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('CreatedBy', models.CharField(blank=True, max_length=15, null=True)),
                ('CreatedDate', models.DateField(auto_now=True)),
                ('ModifiedBy', models.CharField(blank=True, max_length=15, null=True)),
                ('ModifiedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblStuCourse',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mobileno', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=100)),
                ('regdate1', models.DateField(auto_now=True)),
                ('modifiedBy', models.CharField(blank=True, max_length=15, null=True)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tblStudentRegistration',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('mobileno', models.CharField(max_length=15)),
                ('Course', models.CharField(max_length=100)),
                ('coursefee', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=600)),
                ('Password', models.CharField(max_length=30)),
                ('regdate1', models.DateField(auto_now=True)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tblStuquery',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=25, null=True)),
                ('mobileno', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=25)),
                ('query', models.CharField(max_length=500)),
                ('queryans', models.CharField(max_length=500)),
                ('CreatedDate', models.DateField(auto_now=True)),
                ('ModifiedBy', models.CharField(blank=True, max_length=15, null=True)),
                ('ModifiedDate', models.DateField(auto_now=True)),
                ('isCompleted', models.BooleanField(default=False, null=True)),
                ('isActive', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
