# Generated by Django 4.2.18 on 2025-02-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0007_course_enrollment_link_course_roadmap_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='roadmap',
        ),
    ]
