# Generated by Django 4.2.18 on 2025-02-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0008_remove_course_roadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('experienced', 'Experienced')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
