# Generated by Django 4.2.18 on 2025-02-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0011_user_experience_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='experience_level',
        ),
    ]
