# Generated by Django 4.2.18 on 2025-02-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0013_question_quiz_quizattempt_useranswer_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
