# Generated by Django 4.2.18 on 2025-02-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0016_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_pictures/', verbose_name='Profile Picture'),
        ),
    ]
