# Generated by Django 4.2.18 on 2025-02-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0023_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
