# Generated by Django 4.2.18 on 2025-03-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0028_material_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file', null=True, upload_to='course_videos/'),
        ),
        migrations.AddField(
            model_name='material',
            name='video_url',
            field=models.URLField(blank=True, help_text='Video embed URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.TextField(blank=True, help_text='Text content', null=True),
        ),
    ]
