# Generated by Django 4.2.18 on 2025-03-09 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0029_material_video_file_material_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='material',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, help_text='Text content or video embed URL'),
            preserve_default=False,
        ),
    ]
