# Generated by Django 4.2.18 on 2025-03-10 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0040_remove_material_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, help_text='Text content or video embed URL'),
            preserve_default=False,
        ),
    ]
