# Generated by Django 4.2.18 on 2025-03-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0045_enrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
