# Generated by Django 4.2.18 on 2025-03-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgs', '0047_roadmap_roadmapmilestone_roadmapsection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmapmilestone',
            name='section',
        ),
        migrations.RemoveField(
            model_name='roadmapresource',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='roadmapsection',
            name='roadmap',
        ),
        migrations.DeleteModel(
            name='Roadmap',
        ),
        migrations.DeleteModel(
            name='RoadmapMilestone',
        ),
        migrations.DeleteModel(
            name='RoadmapResource',
        ),
        migrations.DeleteModel(
            name='RoadmapSection',
        ),
    ]
